services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
  frontend:
    build: ./client
    ports:
      - "3001:3000"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: apartment_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: